import { WidgetDefinition } from '@/types/widget';

export const widgetRegistry: Record<string, WidgetDefinition> = {
  server_summary: {
    type: 'server_summary',
    displayName: 'Server Summary',
    description: 'Compact overview showing server name, online status, and basic vitals',
    icon: 'server',
    category: 'utility',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    refreshInterval: 15,
    backgroundPollable: true,
    defaultPollInterval: 30,
    defaultTTL: 300,
    storageMode: 'latest_ttl',
  },
  os_info: {
    type: 'os_info',
    displayName: 'OS Info',
    description: 'Operating system, kernel, hostname, uptime',
    icon: 'monitor',
    category: 'system',
    defaultSize: { w: 4, h: 2 },
    minSize: { w: 2, h: 2 },
    refreshInterval: 60,
    backgroundPollable: true,
    defaultPollInterval: 86400,
    defaultTTL: 15552000,
    storageMode: 'change_only',
  },
  cpu_memory: {
    type: 'cpu_memory',
    displayName: 'CPU/Memory',
    description: 'CPU and memory usage gauges with load averages',
    icon: 'cpu',
    category: 'system',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 2, h: 2 },
    refreshInterval: 5,
    backgroundPollable: true,
    defaultPollInterval: 10,
    defaultTTL: 30,
    storageMode: 'latest_ttl',
  },
  disk_usage: {
    type: 'disk_usage',
    displayName: 'Disk Usage',
    description: 'Per-mount disk usage with usage bars',
    icon: 'hard-drive',
    category: 'system',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 2, h: 2 },
    refreshInterval: 30,
    backgroundPollable: true,
    defaultPollInterval: 60,
    defaultTTL: 3600,
    storageMode: 'latest_ttl',
  },
  network: {
    type: 'network',
    displayName: 'Network',
    description: 'Network interfaces with IP addresses',
    icon: 'network',
    category: 'network',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 2, h: 2 },
    refreshInterval: 30,
    backgroundPollable: true,
    defaultPollInterval: 60,
    defaultTTL: 3600,
    storageMode: 'latest_ttl',
  },
  system_services: {
    type: 'system_services',
    displayName: 'System Services',
    description: 'Running system services with status',
    icon: 'settings',
    category: 'system',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    refreshInterval: 30,
    backgroundPollable: true,
    defaultPollInterval: 30,
    defaultTTL: 300,
    storageMode: 'change_only',
  },
  gpu_monitoring: {
    type: 'gpu_monitoring',
    displayName: 'GPU Monitoring',
    description: 'NVIDIA GPU stats (VRAM, utilization, temperature)',
    icon: 'cpu',
    category: 'system',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    refreshInterval: 10,
    backgroundPollable: true,
    defaultPollInterval: 30,
    defaultTTL: 300,
    storageMode: 'latest_ttl',
  },
  ollama_status: {
    type: 'ollama_status',
    displayName: 'Ollama Status',
    description: 'LLM runtime status and model list',
    icon: 'bot',
    category: 'ai',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    refreshInterval: 30,
    backgroundPollable: true,
    defaultPollInterval: 60,
    defaultTTL: 300,
    storageMode: 'latest_ttl',
  },
  ssh_terminal: {
    type: 'ssh_terminal',
    displayName: 'SSH Terminal',
    description: 'Interactive command terminal',
    icon: 'terminal',
    category: 'utility',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    refreshInterval: 0,
    backgroundPollable: false,
  },
  docker_containers: {
    type: 'docker_containers',
    displayName: 'Docker Containers',
    description: 'Container management with start/stop/restart',
    icon: 'box',
    category: 'system',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    refreshInterval: 15,
    backgroundPollable: true,
    defaultPollInterval: 30,
    defaultTTL: 300,
    storageMode: 'change_only',
  },
  custom_command: {
    type: 'custom_command',
    displayName: 'Custom Command',
    description: 'Run custom SSH command',
    icon: 'terminal',
    category: 'utility',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    refreshInterval: 30,
    backgroundPollable: false,  // Don't auto-poll custom commands
  },
  portainer_link: {
    type: 'portainer_link',
    displayName: 'Portainer Link',
    description: 'External Portainer UI link',
    icon: 'external-link',
    category: 'utility',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    refreshInterval: 0,
    backgroundPollable: false,
  },
  os_update_check: {
    type: 'os_update_check',
    displayName: 'OS Update Check',
    description: 'Check for and install OS updates',
    icon: 'refresh-cw',
    category: 'system',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    refreshInterval: 0,
    backgroundPollable: true,
    defaultPollInterval: 86400,
    defaultTTL: 15552000,
    storageMode: 'change_only',
  },
};

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return widgetRegistry[type];
}

export function getWidgetsByCategory(category?: string): WidgetDefinition[] {
  const all = Object.values(widgetRegistry);
  if (!category) return all;
  return all.filter(w => w.category === category);
}