#!/bin/sh


RQLITE_URL="http://localhost:${RQLITE_HTTP_PORT:-4001}"
echo "Waiting for rqlite at ${RQLITE_URL}..."
until wget -q -O /dev/null "${RQLITE_URL}/readyz" 2>/dev/null; do
    sleep 1
done
echo "rqlite is ready."


cd /app
exec ./node_modules/.bin/next start -p ${PORT:-3000}