#!/bin/sh


NODE_NAME="${NODE_NAME:-node1}"
RQLITE_HTTP_PORT="${RQLITE_HTTP_PORT:-4001}"
RQLITE_RAFT_PORT="${RQLITE_RAFT_PORT:-4002}"
RQLITE_DATA_DIR="${RQLITE_DATA_DIR:-/data/rqlite}"


JOIN_FLAG=""
if [ -n "${RQLITE_JOIN}" ]; then
    JOIN_FLAG="-join=${RQLITE_JOIN}"
fi


exec /usr/local/bin/rqlited \
    -node-id="${NODE_NAME}" \
    -http-addr="0.0.0.0:${RQLITE_HTTP_PORT}" \
    -http-adv-addr="localhost:${RQLITE_HTTP_PORT}" \
    -raft-addr="0.0.0.0:${RQLITE_RAFT_PORT}" \
    -raft-adv-addr="localhost:${RQLITE_RAFT_PORT}" \
    ${JOIN_FLAG} \
    "${RQLITE_DATA_DIR}"